version: '3.3'

services:

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "123456"
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
  #web:
  #  build: .
  #  ports:
  #    - "8000:8000"
  #  depends_on:
  #    - postgres
